### ISSUE TITLE
[BUG] 5-Button Remote No Longer works with Media Player Hook

### ISSUE THREAD

**Issue by andrmuel** [EPMatt/awesome-ha-blueprints#21]
**Bug Details**

- Blueprint name: ikea_e1524_e1810.yaml (IKEA 5-Button Remote) & media_player.yaml
- Home Assistant Core Version: 2021.3.4
- Home Assistant Installation Type Home Assistant Core on Debian Bullseye
- I'm using the ZHA integration

**Description**

The 5-Button Remote Controller no longer triggers the media player hook.

**Additional context**

It looks like the commit that broke things for me is 5938d7ec1e4e22659dec7ec89d8251cc060318a6. In particular I think my controller does not support the change of the ZHA action mappings, e.g. `button_left_short` was `[press_257_13_0]` and is now just `['on']`; with the event listener I only see a `zha_event` with command `press` and args `[257, 13, 0]`, but no `on` event.

**Comment by EPMatt** [comment]
Hi @andrmuel, thank you for reporting here.

Actually, the problem is not with your controller. During the upgrade process, action mappings related to ZHA and deCONZ simply got all messed up. I've just updated the blueprint, restoring the correct action mappings.

You can now update the `ikea_e1524_e1810` blueprint, and everything should run smoothly.

I'm sorry for any inconvenience this might have caused. Please let me know if the fix solves your issue. :)

Thanks!

**Comment by andrmuel** [comment]
Hello @EPMatt 

Thank you for the quick reply and the fix. I updated my system to the latest version of the blueprint and can confirm it does indeed fix the issue.

Btw thank you for the blueprints – they do make integration of the IKEA controllers a lot more smooth.

**Comment by EPMatt** [comment]
Hi @andrmuel,
thank you for your feedback, happy to hear that these blueprints are helpful for you. :)
