### ISSUE TITLE
[BUG] E1810 TRADFRI remote - long-press on the direction buttons returns entity_id error

### ISSUE THREAD

**Issue by iammart71** [EPMatt/awesome-ha-blueprints#27]
**Bug Details**

- Blueprint name: Controller - IKEA E1524/E1810 5-Button Remote  ikea_e1524_e1810.yaml
- Home Assistant Core Version: core-2021.4.1
- Home Assistant Installation Type Home Assistant Container
- 
**Description**
E1810 TRADFRI remote - long-press on the 4 direction buttons (up/down/left/right) returns Error while executing automation : not a valid value for dictionary value @ data['entity_id']

**To Reproduce**

1. Create ZHA automation based on ikea_e1524_e1810 blueprint
2. Set up actions on long press  for up/down/left/right(in this case, media player action to select source on a media player device or entity)
3. Trigger the automation via long button press
4. Action does not trigger - See error in logs

**Expected behavior**
The long press should trigger the defined action
In the case of centre-button long press in the blueprint, the action works as expected
Also, setting up a stand-alone automation from blank using device long-press trigger works as expected for the same action
e.g. 
![image](https://user-images.githubusercontent.com/61361762/114202761-6a4f9a80-994f-11eb-9e53-78c77eb3ce33.png)

**Actual Behaviour**
Action does not trigger - long-press on the 4 direction buttons (up/down/left/right) returns Error while executing automation 

**Screenshots**
Example from automation:
![image](https://user-images.githubusercontent.com/61361762/114201680-6111fe00-994e-11eb-9397-08fd062d2fb7.png)

**Additional context**
Logger: homeassistant.components.automation.controller_sonos_remote
Source: components/automation/__init__.py:504
Integration: Automation (documentation, issues)
First occurred: 3:52:26 PM (8 occurrences)
Last logged: 4:11:12 PM

Error while executing automation automation.controller_sonos_remote: not a valid value for dictionary value @ data['entity_id']

Full log:
2021-04-09 16:11:12 ERROR (MainThread) [homeassistant.components.automation.controller_sonos_remote] Controller - Sonos Remote: Choose at step 2: choice 5: Choose at step 1: choice 1: Error executing script. Invalid data for call_service at pos 1: not a valid value for dictionary value @ data['entity_id']
2021-04-09 16:11:12 ERROR (MainThread) [homeassistant.components.automation.controller_sonos_remote] Controller - Sonos Remote: Choose at step 2: choice 5: Error executing script. Invalid data for choose at pos 1: not a valid value for dictionary value @ data['entity_id']
2021-04-09 16:11:12 ERROR (MainThread) [homeassistant.components.automation.controller_sonos_remote] Controller - Sonos Remote: Error executing script. Invalid data for choose at pos 2: not a valid value for dictionary value @ data['entity_id']
2021-04-09 16:11:12 ERROR (MainThread) [homeassistant.components.automation.controller_sonos_remote] Error while executing automation automation.controller_sonos_remote: not a valid value for dictionary value @ data['entity_id']

**Comment by toot** [comment]
I'm facing a similar bug using the  E1743 on/off controller with the light hook - no long press up/down is possible.
Unfortunately I'm not at home over the weekend, I'll be able to post some logs on monday.
I'm using the the core version than iammart71, but my installation runs on a raspberry pi.

**Comment by EPMatt** [comment]
Hi @iammart71 @toot, thank you for reporting here.

When using this blueprint with ZHA, you need to provide a valid `input_text` entity for the `helper_last_controller_event` input. This is also required when using double press events, with any integration. You can read more about the reasons why this helper is required in the [E1810 documentation](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1524_e1810#additional-notes) and [E1743 documentation](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1743#additional-notes).

Please check that you have properly configured this input for the blueprint, and let me know if your issue is solved. :)

Thanks!

**Comment by iammart71** [comment]
Hi @EPMatt
Thanks for clarifying, that seems to work now! I read the template hints to mean that the text helper was only required with double press action...
Cheers
Martin

**Comment by EPMatt** [comment]
Hi @iammart71, thank you for your quick feedback, happy to hear that your issue is solved. :) 
I think we should find a way to better state the text helper is required with ZHA **or** Double press action.

Anyway, I'm keeping this issue open to let @toot report too. :) 

Thank you!

**Comment by iammart71** [comment]
Sure no worries I jumped the gun :)

**Comment by toot** [comment]
@EPMatt thank you for your hint with the input_text entity.
This also solved the issue for me :)

I guess, for different controllers/hooks I need seperate entities? Or is one for alle enough?

I'm rather new to home assistant, so I'm not totally sure.

**Comment by EPMatt** [comment]
Hi @toot,

thank you for your feedback, happy to hear that your issue is solved as well. :)

It is advised to create a separate `input_text` entity for each Controller blueprint you are configuring, since using the same helper for two controllers might result in inconsistent behaviour (if two controllers are actionated at the same time, they might write at the same time on the helper, which will cause race conditions to come in place).

**Comment by EPMatt** [comment]
Hi @toot,

since your original problem is solved I'm now closing this issue. 
If you need additional guidance or help feel free to create a new issue or reopen this one. I'd be happy to answer. :) 

Happy automating!
