### ISSUE TITLE
Wrong URL in readme.md

### ISSUE THREAD

**Issue by alexdelprete** [EPMatt/awesome-ha-blueprints#77]
## Report Details\*

- Documentation URL: https://github.com/EPMatt/awesome-ha-blueprints/blob/main/README.md
- Blueprint name: 

## Description\*

The url in section `Importing a blueprint` of the readme.md is wrong.

## Suggested changes\*

Change link to: https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/

## Additional Details\*

- [ ] I'd like to help improving the documentation by working on this issue.

## Screenshots

![image](https://user-images.githubusercontent.com/7027842/118809094-74e44480-b8aa-11eb-9fc4-6b3a481b8f5b.png)

**Comment by EPMatt** [comment]
Hi @alexdelprete,

thank you for spotting this issue. Actually the README needs a little bit of rewriting, since many of that information is duplicated in the [introduction page in the docs website](https://epmatt.github.io/awesome-ha-blueprints/docs/introduction). I'll link the relevant PR to this issue as soon as the fix is ready. :) 

Thank you!

**Comment by alexdelprete** [comment]
I try to help as I can Matteo. Always feel in debt with people like you that share all this for free. So I try to give back as I can. :)

**Comment by EPMatt** [comment]
@alexdelprete fixed with the linked PR. 
We have a much better README file now. :)

**Comment by alexdelprete** [comment]
Great job.
